# Generated by Django 4.2.7 on 2023-11-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_login_delete_yourmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
